config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  resources :hotels
  resources :rooms, only: :show do
    resources :comments, except: [:index, :show]
    member do
      get :reserve
      get :cancel_reservation
    end
  end

  root 'hotels#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  prepend Draper::CanCanCan

  def initialize(user)
    return unless user

    if user.admin?
      can :manage, Hotel
      can :manage, Comment
      can :cancel_reservation, Room
      can :create_comment, Room
    else
      can :read, Hotel
      can :create_comment, Room, user_id: user.id
      can :update, Comment, user_id: user.id
      can :destroy, Comment, user_id: user.id
      can :reserve, Room
    end

    can :read, Room
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/builders/comment_builder.rb
module Builders
  class CommentBuilder
    attr_reader :comment

    def initialize(comment)
      @comment = comment
    end

    def valid?
      @comment.validate
      check_room_reserved_by_user
      @comment.errors.size.zero?
    end

    def add_body(val)
      @comment.body = val
    end

    def add_room(val)
      @comment.room = val
    end

    def add_user(val)
      @comment.user = val
    end

    def save
      return false unless valid?
      @comment.save
    end

    private

    def check_room_reserved_by_user
      return true if @comment.room.reserved_by?(@comment.user)
      return true if @comment.user.admin?
      @comment.errors.add(:user, 'Room should be reserved by user')
      false
    end
  end
end

app/models/builders/hotel_builder.rb
module Builders
  class HotelBuilder
    attr_reader :hotel

    def initialize(hotel)
      @hotel = hotel
      reset_free_room_count
    end

    def valid?
      @hotel.valid?
    end

    def add_name(val)
      @hotel.name = val
    end

    def add_room_count(val)
      @hotel.room_count = val
      reset_free_room_count
    end

    def save
      return false unless valid?
      (1..@hotel.room_count).each do |i|
        @hotel.rooms << Room.new(room_number: i, reserved: false)
      end
      @hotel.save
    end

    private
    def reset_free_room_count
      @hotel.free_room_count = @hotel.room_count
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :room
  belongs_to :user

  scope :order_created_desc, -> { order(created_at: :desc) }

  validates_presence_of :body

  def author?(user)
    self.user == user
  end
end

app/models/hotel.rb
class Hotel < ApplicationRecord
  has_many :rooms, dependent: :destroy

  validates_presence_of :name
  validates :room_count, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :free_room_count, presence: true, numericality: { greater_than_or_equal_to: 0 }

  scope :by_free_count_desc, -> { order(free_room_count: :desc) }

  def reserved_room_count
    room_count - free_room_count
  end

  def update_free_rooms_count
    update(free_room_count: rooms.where(reserved: false).count)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :hotel
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy

  scope :order_by_reserved_and_name, -> { order(reserved: :asc, room_number: :asc) }

  default_scope { order_by_reserved_and_name }

  validates_presence_of :room_number

  def reserved_by?(user)
    self.user == user
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :rooms
  has_many :comments

  validates_presence_of :firstname, :lastname

  def full_name
    [firstname, lastname].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  helper_method :is_admin?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.html { redirect_to root_url, alert: exception.message }
    end
  end

  def is_admin?
    signed_in? ? current_user.admin : false
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource except: [:new, :create]
  before_action :set_room
  before_action :authorize_create_comment, only: [:new, :create]
  before_action :set_comment, only: [:edit, :update, :destroy]

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment      = Comment.new(comment_params)
    @comment.room = @room
    @comment.user = current_user

    respond_to do |format|
      if Builders::CommentBuilder.new(@comment).save
        format.html { redirect_to @room, notice: 'Comment was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @room, notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @room, notice: 'Comment was successfully destroyed.' }
    end
  end

  private

  def authorize_create_comment
    authorize! :create_comment, @room
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  load_and_authorize_resource except: :index
  skip_before_action :authenticate_user!, only: :index
  before_action :set_hotel, only: [:show, :destroy]

  def index
    @hotels = Hotel.all.by_free_count_desc
  end

  def show
    @rooms = @hotel.rooms.decorate
  end

  def new
    @hotel = Hotel.new
  end

  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if Builders::HotelBuilder.new(@hotel).save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
    end
  end

  private
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    def hotel_params
      params.require(:hotel).permit(:name, :room_count)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:firstname, :lastname, :email, :admin, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :lastname, :email, :admin, :password, :password_confirmation, :current_password)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  load_and_authorize_resource
  before_action :set_room, only: [:show, :reserve, :cancel_reservation]

  def show
    @room     = @room.decorate
    @comments = @room.comments.includes(:user).order_created_desc
  end

  def reserve
    if RoomReservation.reserve_room(@room, current_user)
      redirect_to @room
    else
      redirect_to @room, alert: 'An error occurred during reservation'
    end
  end

  def cancel_reservation
    if RoomReservation.cancel_reservation(@room)
      redirect_to @room.hotel
    else
      redirect_to @room, alert: 'An error occurred during canceling reservation'
    end
  end

  private
  def set_room
    @room = Room.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
  def format_date(date)
    date.strftime('%d.%m.%Y')
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def reservation_link(room)
    if can?(:reserve, room) && !room.reserved?
      link_to t('rooms.reserve'), reserve_room_path(room)
    elsif room.reserved? && room.reserved_by?(current_user)
      t('rooms.reserved_by_you')
    end
  end
end

app/views/comments/_form.html.slim
= form_for [@room, @comment], html: { class: "form-horizontal" } do |f|
  = render partial: 'shared/errors', locals: {object: @comment}
  .form-group
    .col-md-10
      = f.text_area :body, class: 'text_field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit t('save'), class: 'btn btn-primary'
      = link_to t('helpers.links.cancel'), room_path(@room), class: 'btn btn-default'

app/views/comments/edit.html.slim
div class="page-header"
  h1 =t('helpers.titles.edit')
= render partial: "form"

app/views/comments/new.html.slim
.page-header
  h1 = "#{@room.decorate.name} #{t('comments.add')}"
= render partial: 'form'

app/views/hotels/_form.html.slim
= form_for @hotel, html: { class: 'form-horizontal' } do |f|
  = render partial: 'shared/errors', locals: {object: @hotel}
  .form-group
    = f.label :name, class: 'control-label col-md-2'
    .col-md-10
      = f.text_field :name, class: 'text_field form-control'
  .form-group
    = f.label :room_count, class: 'control-label col-md-2'
    .col-md-10
      = f.number_field :room_count, class: 'text_field form-control'
  .form-group
    .col-md-offset-2.col-md-10
      = f.submit t('save'), class: 'btn btn-primary'
      = link_to t('helpers.links.cancel'), hotels_path, class: 'btn btn-default'

app/views/hotels/_hotel.html.slim
.b-widget
  .b-widget-head
    = link_to hotel.name, hotel
    .b-widget-head-action
      - if can? :destroy, hotel
        = link_to t('helpers.links.destroy'), hotel_path(hotel), method: 'delete',
                data: { confirm: t('helpers.links.confirm') }
  .b-widget-content
    = "#{t('hotels.free_rooms')} #{hotel.free_room_count}"
    br
    = "#{t('hotels.reserved_rooms')} #{hotel.reserved_room_count}"

app/views/hotels/index.html.slim
.row
  .col-md-8.col-md-offset-2
    - if can? :create, Hotel
      .ho-create-link
        = link_to t('hotels.add'), new_hotel_path, class: 'btn-sm btn-primary'
    - @hotels.each do |hotel|
      = render partial: 'hotels/hotel', locals: { hotel: hotel }

app/views/hotels/new.html.slim
.page-header
  h1 = t('hotels.add')
= render partial: "form"

app/views/hotels/show.html.slim
.row
  .col-md-8.col-md-offset-2
    = render partial: 'hotels/hotel', locals: { hotel: @hotel }
    - @rooms.each do |room|
      .b-widget
        .b-widget-head
          = link_to "#{room.name} - #{room.reservation_status}", room
          .b-widget-head-action
            - if can?(:cancel_reservation, room) && room.reserved?
              = link_to t('rooms.cancel_reservation'), cancel_reservation_room_path(room)

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t('reservation_service')
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    nav.navbar.navbar-default.navbar-fixed-top role="navigation"
      .container
        .navbar-header
          button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#{root_path}" #{t('reservation_service')}
        .navbar-collapse.collapse.navbar-responsive-collapse
          ul.nav.navbar-nav
            li
              = active_link_to t('home'), root_path, wrap_tag: :li, active: [['hotels'], ['index', 'show', 'edit']]
          ul.nav.navbar-nav.pull-right
            - if user_signed_in?
              li.name
                = current_user.full_name
              li
                = link_to t('log_out'), destroy_user_session_path, method: :delete
            - else
              li
                = link_to t('devise.sessions.new.sign_in'), new_user_session_path
              li
                = link_to t('devise.registrations.new.sign_up'), new_user_registration_path

    .container
      .row
        .col-md-12
          /= bootstrap_flash
          - if notice
            p.alert.alert-success = notice
          - if alert
            p.alert.alert-danger = alert
          = yield

app/views/rooms/show.html.slim
.row
  .col-md-8.col-md-offset-2
    = render partial: 'hotels/hotel', locals: { hotel: @room.hotel }
    .b-widget
      .b-widget-head
        = "#{@room.name} - #{@room.reservation_status}"
        .b-widget-head-action
          = reservation_link(@room)
    .b-widget
      .b-widget-head
        = "Комментарии (#{@comments.count})"
        .b-widget-head-action
          - if can? :create_comment, @room
            = link_to t('comments.add'), new_room_comment_path(@room)
      .b-widget-content
        ul.list-unstyled
          - @comments.each do |comment|
            li
              .ro-message
                .ro-message-info
                  .ro-message-name
                    = comment.user.full_name
                  .ro-message-time
                    = format_date comment.created_at
                .ro-message-content
                  = comment.body
                br
                .ro-message-actions
                  - if can? :edit, comment
                    = link_to t('helpers.links.edit'), edit_room_comment_path(@room, comment), class: 'btn btn-xs', title: t('helpers.links.edit')
                  - if can? :update, comment
                    = link_to t('helpers.titles.delete'), room_comment_path(@room, comment),
                            method: :delete, data: { confirm: t('helpers.links.confirm') },
                            class: 'btn btn-xs', title: t('helpers.links.destroy')

app/views/shared/_errors.html.slim
- if object.errors.any?
  #error_explanation
    .row
      .col-md-12
        .alert.alert-danger
          .font100
            h2.label.label-danger
              = t('errors.template.body')
            ol
              - object.errors.full_messages.each do |msg|
                li
                  = msg